import AgentPetEvents

public typealias ClaudeHookRecordResult = AgentHookRecordResult
public typealias ClaudeHookRecorderError = AgentHookRecorderError
public typealias ClaudeHookRecorder = AgentHookRecorder
