import AgentPetEvents

public typealias ClaudeEventLogReaderError = AgentEventLogReaderError
public typealias ClaudeEventLogIssue = AgentEventLogIssue
public typealias ClaudeEventReadBatch = AgentEventReadBatch
public typealias ClaudeEventLogReader = AgentEventLogReader
